// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  返回标准初始局面 FEN */
	getInitialBoard: () => __TAURI_INVOKE<string>("get_initial_board"),
	/**  校验 FEN 并返回其规范化形式 */
	parseFen: (fen: string) => typedError<string, string>(__TAURI_INVOKE("parse_fen", { fen })),
	/**  严格校验可用于开始正式对局的自定义局面，并返回规范化 FEN */
	validatePosition: (fen: string) => typedError<string, string>(__TAURI_INVOKE("validate_position", { fen })),
	/**  导出受管会话的当前局面 FEN */
	toFen: () => typedError<string, string>(__TAURI_INVOKE("to_fen")),
	/**
	 *  对局面执行一步走法并返回结果状态
	 * 
	 *  前端视角是纯函数（局面 FEN + ICCS 输入，`MoveResult` 输出）。副作用：当传入
	 *  FEN 与受管会话的当前局面一致且对局未终局时，该走法也会作用于会话，使历史
	 *  （悔棋/重做/认输）与当前对局保持同步
	 */
	makeMove: (fen: string, iccs: string) => typedError<MoveResult, string>(__TAURI_INVOKE("make_move", { fen, iccs })),
	/**  返回给定局面上当前走方的全部合法 ICCS 走法 */
	getLegalMoves: (fen: string) => typedError<string[], string>(__TAURI_INVOKE("get_legal_moves", { fen })),
	/**  返回给定局面上指定起始格（row: 0..9, col: 0..8）棋子的全部候选目标格（包含会送将/未应将的点位，供 UI 展示落点与反馈） */
	getCandidateMoves: (fen: string, row: number, col: number) => typedError<string[], string>(__TAURI_INVOKE("get_candidate_moves", { fen, row, col })),
	/**  返回局面上一步走法的繁体中文记法 */
	toChineseNotation: (fen: string, iccs: string) => typedError<string, string>(__TAURI_INVOKE("to_chinese_notation", { fen, iccs })),
	/**  报告局面上当前走方是否被将军 */
	isInCheck: (fen: string) => typedError<boolean, string>(__TAURI_INVOKE("is_in_check", { fen })),
	/**  纯函数式重放历史和 PV 前缀，返回规则快照；不会写入受管 GameState */
	previewLine: (request: PreviewRequest) => typedError<PreviewSnapshot, string>(__TAURI_INVOKE("preview_line", { request })),
	/**  校验整条 PV 后一次性提交，任一步非法都不改变正式对局 */
	applyMoveLine: (request: ApplyMoveLineRequest) => typedError<GameSnapshot, string>(__TAURI_INVOKE("apply_move_line", { request })),
	/**  开始新对局会话，可选从给定 FEN 开始（默认初始局面） */
	newGame: (fen: string | null) => typedError<GameSnapshot, string>(__TAURI_INVOKE("new_game", { fen })),
	/**  切换当前对局使用的规则档案 */
	setRuleProfile: (profile: RuleProfile) => typedError<GameSnapshot, string>(__TAURI_INVOKE("set_rule_profile", { profile })),
	/**  返回当前对局会话的快照 */
	gameResult: () => typedError<GameSnapshot, string>(__TAURI_INVOKE("game_result")),
	/**  悔掉会话中的上一步 */
	undoMove: () => typedError<GameSnapshot, string>(__TAURI_INVOKE("undo_move")),
	/**  重新应用刚悔掉的这一步 */
	redoMove: () => typedError<GameSnapshot, string>(__TAURI_INVOKE("redo_move")),
	/**  将当前对局会话定位到指定步数游标（0 为起始局面） */
	jumpTo: (ply: number) => typedError<GameSnapshot, string>(__TAURI_INVOKE("jump_to", { ply })),
	/**  标记指定一方（`red` / `black`）认输 */
	resign: (color: string) => typedError<GameSnapshot, string>(__TAURI_INVOKE("resign", { color })),
	/**  用于验证 IPC 桥接已连通的握手命令 */
	ping: () => __TAURI_INVOKE<string>("ping"),
	sessionGet: () => __TAURI_INVOKE<SessionSnapshot>("session_get"),
	sessionNew: (token: SessionToken, options: NewGameOptions) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_new", { token, options })),
	sessionTargets: (token: SessionToken, from: Position) => typedError<string[], SessionError>(__TAURI_INVOKE("session_targets", { token, from })),
	sessionMove: (token: SessionToken, iccs: string) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_move", { token, iccs })),
	sessionUndo: (token: SessionToken) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_undo", { token })),
	sessionRedo: (token: SessionToken) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_redo", { token })),
	sessionJump: (token: SessionToken, ply: number) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_jump", { token, ply })),
	sessionResign: (token: SessionToken, side: Color) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_resign", { token, side })),
	sessionOfferDraw: (token: SessionToken, side: Color) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_offer_draw", { token, side })),
	sessionRespondDraw: (token: SessionToken, offerId: string, side: Color, accept: boolean) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_respond_draw", { token, offerId, side, accept })),
	sessionCancelDraw: (token: SessionToken, offerId: string, side: Color) => typedError<SessionSnapshot, SessionError>(__TAURI_INVOKE("session_cancel_draw", { token, offerId, side })),
	/**  启动（或重启）引擎子进程并开始转发其事件 */
	engineStart: (config: EngineConfig) => typedError<EngineInfo, string>(__TAURI_INVOKE("engine_start", { config })),
	/**  开始对给定局面进行分析 */
	engineAnalyze: (request: AnalysisRequest) => typedError<AnalysisStartResult, string>(__TAURI_INVOKE("engine_analyze", { request })),
	/**  中断当前搜索并发出引擎的最佳着法 */
	engineMoveNow: () => typedError<null, string>(__TAURI_INVOKE("engine_move_now")),
	/**  触发当前引擎握手声明的 button 类型动态选项 */
	engineTriggerButtonOption: (name: string) => typedError<null, string>(__TAURI_INVOKE("engine_trigger_button_option", { name })),
	/**  排除给定 ICCS 走法后重新搜索 */
	engineChangeTactic: (request: AnalysisRequest) => typedError<AnalysisStartResult, string>(__TAURI_INVOKE("engine_change_tactic", { request })),
	/**  停止引擎子进程及其事件转发任务 */
	engineStop: () => typedError<null, string>(__TAURI_INVOKE("engine_stop")),
	/**  报告引擎会话是否在运行或正在分析 */
	engineStatus: () => typedError<boolean, string>(__TAURI_INVOKE("engine_status")),
	/**  查询当前引擎运行中的原始协议日志 */
	engineProtocolLog: (analysisSessionId: string | null) => typedError<EngineRawLine[], string>(__TAURI_INVOKE("engine_protocol_log", { analysisSessionId })),
	/**  将当前运行中的原始协议日志导出为文本，不改变后端日志缓冲 */
	engineExportProtocolLog: (path: string, analysisSessionId: string | null) => typedError<null, string>(__TAURI_INVOKE("engine_export_protocol_log", { path, analysisSessionId })),
	/**
	 *  弹出系统原生文件对话框，按 `kind` 过滤可选文件类型
	 *  `nnue` 过滤权重文件，`book` 过滤 `.bh` 开局库，`folder` 选择目录；其它取值按引擎可执行文件处理，
	 *  不做扩展名过滤，以兼容 Unix 上无扩展名的引擎
	 */
	enginePickFile: (kind: string | null) => typedError<string | null, string>(__TAURI_INVOKE("engine_pick_file", { kind })),
	/**
	 *  在线下载、解压并装配内置引擎（如皮卡鱼 Pikafish）
	 *  下载与解压期间不持有配置锁，避免长时间阻塞其它配置读写；装配完成后先对
	 *  staging 产物做一次协议探活，再替换正式目录并写入 `config.json`。探活或配置
	 *  写入失败都不会破坏现有安装
	 */
	engineDownloadBuiltin: (profileId: string) => typedError<EngineProfile, string>(__TAURI_INVOKE("engine_download_builtin", { profileId })),
	/**
	 *  清除内置引擎已下载的本地文件，并把它重置为未安装状态
	 *  只删除本应用在 `engines/<install_key>` 下创建的内容；自定义本地引擎不经过
	 *  该目录，因此不受影响
	 */
	engineRemoveBuiltin: (profileId: string) => typedError<EngineProfile, string>(__TAURI_INVOKE("engine_remove_builtin", { profileId })),
	/**  从磁盘加载并解析棋谱（`.xqf`/`.pgn`） */
	manualLoad: (path: string) => typedError<ChessManual, string>(__TAURI_INVOKE("manual_load", { path })),
	/**  弹出棋谱文件选择器；普通棋谱与揭棋文档使用互不混淆的 action */
	manualPickFile: (action: string) => typedError<string | null, string>(__TAURI_INVOKE("manual_pick_file", { action })),
	/**  保存揭棋文档；完整身份从锁内克隆的 Rust 对局直接进入文件服务 */
	jieqiDocumentSave: (token: SessionToken, path: string, kind: JieqiDocumentKind, metadata: JieqiDocumentMetadata, annotations: { [key in number]: string }, editRevision: string) => typedError<JieqiDocumentReceipt, SessionError>(__TAURI_INVOKE("jieqi_document_save", { token, path, kind, metadata, annotations, editRevision })),
	/**  打开揭棋文档；文件在锁外完整解析，提交候选时统一停止引擎并复核 token */
	jieqiDocumentOpen: (token: SessionToken, path: string) => typedError<JieqiDocumentOpenResult, SessionError>(__TAURI_INVOKE("jieqi_document_open", { token, path })),
	/**  解析文本棋谱；文件格式和字节编码仍由 `ManualService` 负责 */
	manualParseText: (format: string, text: string) => typedError<ChessManual, string>(__TAURI_INVOKE("manual_parse_text", { format, text })),
	/**  将棋谱保存为 `.pgn` 到磁盘 */
	manualSave: (path: string, manual: ChessManual) => typedError<null, string>(__TAURI_INVOKE("manual_save", { path, manual })),
	/**  将棋谱规范化导出为 XQF v10 到磁盘 */
	manualSaveXqf: (path: string, manual: ChessManual, version: number) => typedError<null, string>(__TAURI_INVOKE("manual_save_xqf", { path, manual, version })),
	/**  将棋谱导出为 PGN 字符串（不写入文件） */
	manualExportPgn: (manual: ChessManual) => __TAURI_INVOKE<string>("manual_export_pgn", { manual }),
	/**  从磁盘加载一个 `.bh` 开局库（按路径幂等） */
	bookLoad: (path: string) => typedError<null, string>(__TAURI_INVOKE("book_load", { path })),
	/**  按路径卸载一个已加载的开局库 */
	bookUnload: (path: string) => typedError<null, string>(__TAURI_INVOKE("book_unload", { path })),
	/**  卸载所有已加载的开局库 */
	bookClear: () => typedError<null, string>(__TAURI_INVOKE("book_clear")),
	/**  返回当前已加载开局库的路径列表 */
	bookLoaded: () => typedError<string[], string>(__TAURI_INVOKE("book_loaded")),
	/**  查询开局库在指定局面下的候选招法（根据配置综合本地 .bh 库与在线象棋云库） */
	bookQuery: (fen: string) => typedError<BookMove[], string>(__TAURI_INVOKE("book_query", { fen })),
	/**  设置象棋云库 (chessdb.cn) 是否启用 */
	bookSetCloudEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("book_set_cloud_enabled", { enabled })),
	/**  设置象棋云库协同查询模式（协同/仅云库/仅本地/合并） */
	bookSetCloudMode: (mode: CloudBookMode) => typedError<null, string>(__TAURI_INVOKE("book_set_cloud_mode", { mode })),
	/**  获取当前象棋云库状态（启用开关与协同模式） */
	bookGetCloudStatus: () => typedError<CloudBookStatus, string>(__TAURI_INVOKE("book_get_cloud_status")),
	/**  读取当前持久化配置。若文件尚不存在则返回标准初始默认配置 */
	configLoad: () => typedError<AppConfig, string>(__TAURI_INVOKE("config_load")),
	/**  保存配置（采用文件系统原子替换，杜绝异常断电导致配置损坏为 0 字节） */
	configSave: (config: AppConfig) => typedError<null, string>(__TAURI_INVOKE("config_save", { config })),
	/**  获取当前配置文件的物理存储路径及是否处于便携模式 */
	configGetLocation: () => typedError<ConfigLocationInfo, string>(__TAURI_INVOKE("config_get_location")),
};

/* Types */
/**  引擎思考与变例分析配置 */
export type AnalysisConfig = {
	mode: AnalysisMode,
	value: number,
	multi_pv: number,
	engine_delay_ms: number,
	book_delay_ms: number,
};

/**  引擎思考限制模式 */
export type AnalysisMode = "fixed_time" | "fixed_depth" | "fixed_nodes" | "infinite";

/**  前端发起的一次外部引擎分析请求 */
export type AnalysisRequest = {
	analysis_session_id: string,
	position: EnginePositionContext,
	constraint: RootMoveConstraint,
	config: AnalysisConfig,
};

/**  分析启动结果，明确告知前端根节点约束是否真的生效 */
export type AnalysisStartResult = {
	constraint_status: ConstraintApplicationStatus,
	started: boolean,
};

/**  沧浪象棋全局持久化配置模型 */
export type AppConfig = {
	theme: string,
	boardOrientation: string,
	showCoordinates: boolean,
	showEngineArrow: boolean,
	animations: boolean,
	moveAnimationSeconds: number | null,
	soundEnabled: boolean,
	defaultRuleProfile: string,
	openingBookPaths: string[],
	cloudBookEnabled: boolean,
	cloudBookMode: CloudBookMode,
	engineProfiles: EngineProfile[],
	activeEngineId: string | null,
	analysisMode: AnalysisMode,
	analysisLimitValue: number,
	multiPv: number,
};

/**  将预览前缀原子应用到正式对局 */
export type ApplyMoveLineRequest = {
	expected_fen: string,
	moves: string[],
};

/**  开局库招法条目 */
export type BookMove = {
	iccs: string,
	notation: string | null,
	score: number,
	win_count: number,
	draw_count: number,
	lose_count: number,
	win_rate: number | null,
	note: string | null,
	source: string,
};

export type CapturedPieceView = { type: "none" } | { type: "revealed"; kind: JieqiPublicKind } | { type: "hidden" };

/**  完整棋谱数据模型 */
export type ChessManual = {
	title: string,
	date: string | null,
	red_player: string | null,
	black_player: string | null,
	event_name: string | null,
	start_fen: string,
	root: ManualNode,
};

/**  云端与本地开局库协同查询策略 */
export type CloudBookMode = 
/**  协同模式：本地优先，脱谱或无本地库时自动查询云库（推荐） */
"hybrid" | 
/**  纯云库模式：仅查询象棋云库 */
"cloud_only" | 
/**  纯本地模式：仅查询本地加载的 .bh 库（离线） */
"local_only" | 
/**  合并模式：同时查询本地库与云库，合并去重后按评分排序 */
"merge";

/**  象棋云库当前状态报告 */
export type CloudBookStatus = {
	enabled: boolean,
	mode: CloudBookMode,
};

/**  棋子阵营（红方 / 黑方） */
export type Color = "red" | "black";

/**  配置文件位置与便携模式状态 */
export type ConfigLocationInfo = {
	filePath: string,
	isPortable: boolean,
	/**
	 *  配置文件当前是否已存在。前端据此判断是否为首次运行：默认配置自带
	 *  内置引擎，不能再用“档案列表为空”推断磁盘上有没有用户数据
	 */
	exists: boolean,
};

/**  根节点约束应用结果，供前端显示真实状态 */
export type ConstraintApplicationStatus = "applied" | "not_applied" | "unsupported";

export type DrawOffer = {
	id: string,
	proposer: Color,
};

/**  引擎协议与根节点约束能力 */
export type EngineCapabilities = {
	protocol: string,
	searchmoves: boolean,
	banmoves: boolean,
	ponder: boolean,
	multi_pv: boolean,
};

/**  外部象棋引擎配置 */
export type EngineConfig = {
	path: string,
	protocol: string,
	options: { [key in string]: string } | null,
	nnue_path: string | null,
};

/**  引擎握手后确认的身份与协议诊断信息 */
export type EngineInfo = {
	name: string | null,
	protocol: string,
	ready: boolean,
	diagnostic: string | null,
	option_descriptors: EngineOptionDescriptor[],
	capabilities: EngineCapabilities,
};

/**  引擎握手声明的动态选项 */
export type EngineOptionDescriptor = {
	name: string,
	option_type: EngineOptionType,
	default: EngineOptionValue | null,
	min: number | null,
	max: number | null,
	step: number | null,
	vars: string[],
};

/**  引擎动态选项的声明类型 */
export type EngineOptionType = "check" | "spin" | "combo" | "string" | "file" | "button";

/**
 *  引擎动态选项的持久化值
 *  按引擎握手声明的类型保存，只有在协议边界才转换成字符串
 */
export type EngineOptionValue = { kind: "bool"; value: boolean } | { kind: "integer"; value: number } | { kind: "float"; value: number | null } | { kind: "enum"; value: string } | { kind: "string"; value: string } | { kind: "path"; value: string };

/**  引擎原始协议流的方向，保留 stdout/stderr 差异供诊断界面筛选 */
export type EngineOutputStream = "stdin" | "stdout" | "stderr" | "lifecycle";

/**  引擎协议使用的局面上下文 */
export type EnginePositionContext = {
	start_fen: string,
	history: string[],
	current_fen: string,
};

/**  外部引擎配置档案项 */
export type EngineProfile = {
	id: string,
	name: string,
	path: string,
	protocol: string,
	threads: number | null,
	hashMb: number | null,
	nnuePath: string | null,
	optionOverrides?: { [key in string]: EngineOptionValue },
	/**  内置发行注册表中的可比较修订；自定义引擎为空字符串 */
	releaseRevision?: string,
	/**  最近一次成功安装并探活的修订；旧配置缺失时为空字符串 */
	installedRevision?: string,
	isBuiltin: boolean,
	downloadUrl: string | null,
	description: string | null,
};

/**  在协议边界采集的原始行；`raw` 保留 CRLF、空行和长行内容 */
export type EngineRawLine = {
	run_id: string,
	analysis_session_id: string | null,
	timestamp_ms: number,
	sequence: number,
	stream: EngineOutputStream,
	raw: string,
};

/**  受管 [`GameState`] 会话的轻量序列化视图 */
export type GameSnapshot = {
	/**  当前局面 FEN（保持向后兼容，等同于 current_fen） */
	fen: string,
	/**  对局起始局面的 FEN */
	start_fen: string,
	/**  当前呈现局面的 FEN */
	current_fen: string,
	/**  当前所处的步数游标深度 (0 表示处于起始局面，等于 history.len() 表示处于最新局面) */
	current_ply: number,
	/**  完整主线历史（包含已走步与可重做步） */
	history: PlyRecord[],
	/**  对局结果：`ongoing` | `redwin` | `blackwin` | `draw` */
	result: string,
	/**  当前是否轮到红方走棋 */
	red_to_move: boolean,
	/**  当前轮到的一方是否被将军 */
	in_check: boolean,
	/**  当前是否可悔棋 */
	can_undo: boolean,
	/**  当前是否可重做 */
	can_redo: boolean,
	/**  当前对局使用的规则档案 */
	rule_profile: RuleProfile,
	/**  当前局面的完整重复次数 */
	repetition_count: number,
	/**  达到重复阈值时给裁判的规则解释 */
	repetition_explanation: string | null,
	/**  机器可读的规则裁判状态 */
	rule_status: RuleStatus,
	/**  机器可读的规则解释 */
	rule_explanation: RuleExplanation | null,
};

export type JieqiCapability = {
	enabled: boolean,
	reason: JieqiCapabilityReason | null,
};

export type JieqiCapabilityReason = "wrong_variant" | "read_only" | "duel_policy" | "finished" | "not_at_head" | "pending_draw" | "no_history" | "no_future";

export type JieqiDocumentKind = "private_game" | "public_replay";

export type JieqiDocumentMetadata = {
	title: string,
	date: string,
	red_player: string,
	black_player: string,
	event_name: string,
};

export type JieqiDocumentOpenResult = {
	snapshot: SessionSnapshot,
	document: JieqiDocumentPublic,
};

export type JieqiDocumentPublic = {
	kind: JieqiDocumentKind,
	metadata: JieqiDocumentMetadata,
	annotations: { [key in number]: string },
};

export type JieqiDocumentReceipt = {
	game_id: string,
	content_revision: string,
	edit_revision: string,
	kind: JieqiDocumentKind,
};

export type JieqiPieceView = { state: "hidden"; position: Position; color: Color; move_as: JieqiPublicKind } | { state: "revealed"; position: Position; color: Color; kind: JieqiPublicKind };

export type JieqiPlayMode = "duel" | "training";

export type JieqiPositionViewV1 = {
	turn: Color,
	pieces: JieqiPieceView[],
};

export type JieqiPublicKind = "king" | "advisor" | "bishop" | "knight" | "rook" | "cannon" | "pawn";

/**
 *  棋谱变例树节点（多叉树结构）
 *  `children[0]` 为主线后继节点，`children[1..]` 为变例分支节点
 */
export type ManualNode = {
	id: number,
	mv: Move | null,
	chinese_notation: string,
	comment: string | null,
	score: number | null,
	children: ManualNode[],
};

/**
 *  表示一步走法（起始格到目标格）
 *  支持 ICCS 4 字符（如 "h2e2"）编解码
 */
export type Move = {
	from: Position,
	to: Position,
};

/**
 *  规则裁判关注的走法作用
 *  可直接确认的类别与待细化的规则类别分开保存
 *  `Capture`、`Check` 和 `Checkmate` 可以从当前棋盘直接确认；兑、捉、献、拦
 *  等需要结合循环中的前后手、被攻击子力和规则案例判断，先保留为稳定的分类值，
 *  由后续裁判器逐步细化，不在信息不足时臆判
 */
export type MoveEffect = "check" | "checkmate" | "capture" | "exchange" | "chase" | "joint_chase" | "sacrifice" | "block" | "idle" | "pending";

/**  对单个局面执行无状态 `make_move` 的结果 */
export type MoveResult = {
	/**  合法走后得到的新局面 FEN（非法时返回输入 FEN） */
	fen: string,
	/**  实际应用的 ICCS 走法 */
	iccs: string,
	/**  该走法的繁体中文记法（非法时为空串） */
	chinese_notation: string,
	/**  该走法在当前局面上是否合法 */
	legal: boolean,
	/**  走子后轮到的一方是否被将军 */
	check: boolean,
	/**  该走法是否结束对局（绝杀或困毙） */
	game_over: boolean,
};

export type NewGameOptions = { variant: "xiangqi"; fen: string | null; rule_profile: RuleProfile } | { variant: "jieqi"; play_mode: JieqiPlayMode };

export type PlyRecord = {
	ply: number,
	iccs: string,
	notation: string,
	mover: string,
	is_capture: boolean,
	is_check: boolean,
	fen: string,
};

/**
 *  表示象棋棋盘上的一个坐标位置
 *  行：0..=9（0 为黑方底线，9 为红方底线）
 *  列：0..=8（0 为 a 列/黑方左翼，8 为 i 列/黑方右翼）
 */
export type Position = {
	row: number,
	col: number,
};

export type PositionView = { variant: "xiangqi"; fen: string } | { variant: "jieqi"; position: JieqiPositionViewV1 };

/**  只读分析变例预览请求，不修改受管 GameState */
export type PreviewRequest = {
	start_fen: string,
	history: string[],
	pv: string[],
	rule_profile: RuleProfile,
};

/**  分析变例在 core 规则服务中的只读快照 */
export type PreviewSnapshot = {
	fen: string,
	red_to_move: boolean,
	in_check: boolean,
	last_move_iccs: string | null,
	repetition_count: number,
	rule_status: RuleStatus,
	rule_explanation: RuleExplanation | null,
	applied_pv_len: number,
};

export type PublicPly = {
	ply: number,
	iccs: string,
	mover: Color,
	notation: string,
	revealed: JieqiPublicKind | null,
	captured: CapturedPieceView,
	is_check: boolean,
};

/**  当前分析请求的根节点着法约束 */
export type RootMoveConstraint = {
	candidates: string[],
	banned: string[],
	temporary_excluded: string[],
};

/**  一条可展示、可记录的规则解释 */
export type RuleExplanation = {
	code: RuleExplanationCode,
	side: string | null,
	category: MoveEffect | null,
	message: string,
	cycle_length: number | null,
};

/**  面向调用方的规则解释码 */
export type RuleExplanationCode = "checkmate" | "stalemate" | "repetition_needs_judgement" | "prohibited_move_candidate" | "rule_loss" | "rule_draw";

/**
 *  对局使用的象棋竞赛规则档案
 *  `china_2020` 对应中国象棋协会 2020 竞赛规则；`asian_2017` 对应亚洲象棋
 *  联合会 2017 规则，并作为世界规则兼容档案的基础。具体循环裁判由规则服务
 *  根据该档案解释，棋盘走法仍由 `MoveValidator` 统一负责
 */
export type RuleProfile = "china2020" | "asian2017";

/**  当前规则裁判状态 */
export type RuleStatus = "ongoing" | "checkmate" | "stalemate" | "repetition_pending" | "prohibited_move_pending" | "red_loss_by_rule" | "black_loss_by_rule" | "draw_by_rule";

export type SessionCapabilities = {
	move: JieqiCapability,
	undo: JieqiCapability,
	redo: JieqiCapability,
	jump: JieqiCapability,
	resign: JieqiCapability,
	offer_draw: JieqiCapability,
	save_private: JieqiCapability,
	save_public: JieqiCapability,
	edit_annotations: JieqiCapability,
	analyze: JieqiCapability,
	query_book: JieqiCapability,
	edit_position: JieqiCapability,
	use_fen: JieqiCapability,
};

export type SessionError = {
	code: SessionErrorCode,
	message: string,
};

export type SessionErrorCode = "stale_session" | "invalid_input" | "illegal_move" | "operation_unavailable" | "game_finished" | "io_failure";

export type SessionPly = { variant: "xiangqi"; ply: PlyRecord } | { variant: "jieqi"; ply: PublicPly };

export type SessionResult = { type: "ongoing" } | { type: "winner"; winner: Color; reason: SessionResultReason } | { type: "draw" };

export type SessionResultReason = "checkmate" | "stalemate" | "resignation" | "agreement";

export type SessionRules = { variant: "xiangqi"; profile: RuleProfile } | { variant: "jieqi_casual_v1" };

export type SessionSnapshot = {
	game_id: string,
	revision: string,
	content_revision: string,
	position: PositionView,
	start_position: PositionView,
	head_ply: number,
	current_ply: number,
	source: SessionSource,
	rules: SessionRules,
	play_mode: JieqiPlayMode,
	result: SessionResult,
	in_check: boolean,
	history: SessionPly[],
	xiangqi_assessment: XiangqiAssessment | null,
	capabilities: SessionCapabilities,
	draw_offer: DrawOffer | null,
};

export type SessionSource = "local" | "public_replay";

export type SessionToken = {
	game_id: string,
	expected_revision: string,
};

export type XiangqiAssessment = {
	repetition_count: number,
	repetition_explanation: string | null,
	rule_status: RuleStatus,
	rule_explanation: RuleExplanation | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

